# CI for Product Catalog Service

name: Terraform CI

on:
    push:
        branches:
          - main
          - "**"

    pull_request:
        branches:
          - main

    workflow_dispatch:

jobs:
    terraform_plan:
        name: Terraform Plan
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: terraform

        steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Set up terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform_version: 1.7.0

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v6
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Terraform Init
          run: terraform init

        - name: Terraform Format Check
          run: terraform fmt -check

        - name: Terraform Validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan -out=tfplan -lock=false

        - name: Upload Terraform Plan
          uses: actions/upload-artifact@v6
          with:
            name: terraform-plan
            path: terraform/tfplan

        - name: Check file structure
          run: ls -R
    
    terraform_apply:
        name: Terraform Apply
        runs-on: ubuntu-latest
        needs: terraform_plan

        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'

        defaults:
            run:
                working-directory: terraform

        steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Set up terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform_version: 1.7.0

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v6
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Download Terraform Plan
          uses: actions/download-artifact@v8
          with:
            name: terraform-plan

        - name: Check file structure
          run: ls -F

        - name: Terraform Apply
          run: terraform apply -auto-approve terraform-plan/tfplan
          